# Generated by Django 5.2.5 on 2025-08-16 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_alter_newsletter_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='newsletter_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='newsletter_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='sentiment',
            field=models.CharField(default='Neutral', max_length=20),
        ),
    ]
