# Generated by Django 5.2.5 on 2025-08-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sentiment',
            field=models.CharField(default='Neutral', max_length=20),
        ),
    ]
