# Generated by Django 5.2.1 on 2025-08-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
