# Generated by Django 5.2.5 on 2025-08-16 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_article_dislikes_article_likes'),
        ('comment', '0001_initial'),
        ('newsletter', '0007_newsletter_dislikes_newsletter_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='newsletter',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='newsletter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dislike',
            name='newsletter',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='newsletter',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletter'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'article', 'newsletter')},
        ),
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together={('user', 'article', 'newsletter')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'article', 'newsletter')},
        ),
    ]
