# Generated by Django 5.2.5 on 2025-08-16 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_article_dislikes_article_likes'),
        ('comment', '0002_alter_bookmark_unique_together_and_more'),
        ('newsletter', '0007_newsletter_dislikes_newsletter_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletter'),
        ),
    ]
